spring:
  thymeleaf:
    prefix: classpath:/views/
  datasource:
    url: jdbc:postgresql://localhost:5433/account
    username: account
    password: account
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.springframework : error
  file:
    path: log
    max-size:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'